version: '3'
services:
  node-app:
    build: .
    ports:
      - '5000:4000'
    env_file:
      - ./.env

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
