version: '3'
services:
  node-app:
    build: .
    ports:
      - '5000:4000'
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
