version: '3'
services:
  nginx:
    image: nginx:stable-alpine
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
