version: '3'
services:
  nginx:
    ports:
      - '3000:80' # we map it to port 80 because thats the port my nginx server is listening on (in dev)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=1234
      - SESSION_SECRET=secret

    command: ['npm', 'run', 'dev']
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
