version: '3'
services:
  nginx:
    ports:
      - '80:80' # for production its a different port
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: ['node', 'index.js']
